import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/Header/Header"; // Importera Header-komponenten
import Footer from "../components/Footer/Footer"; // Importera Header-komponenten
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header /> {/* Lägg till Header här för att göra den global */}
       
        {children}
        <Footer /> {/* Lägg till footern här */}
      </body>
    </html>
  );
}
